### ISSUE TITLE
500 internal server error

### ISSUE THREAD

**Issue by meiraa13** [rocketseat-education/nlw-unite-nodejs#6]
preenchi a variavel .env, rodei os comandos npm install e npx prisma db seed mas só recebo erro 500 ao tentar fazer qualque requisição para a api

**Comment by Renansf8** [comment]
Verifica a sua versão do node, estava tendo o mesmo problema, alterei para a versão 20.12.2 e funcionou

**Comment by meiraa13** [comment]
> Verifica a sua versão do node, estava tendo o mesmo problema, alterei para a versão 20.12.2 e funcionou

resolveu aqui, valeu! não sei se ta isso em algum lugar, caso não esteja era bom avisar sobre a versão do node
